<script lang="ts">
 import MoonBirth from '$lib/components/onboarding/MoonBirth.svelte';
 let showBirth = $state(false);
 import ChatExample from '$lib/components/chat/ChatExample.svelte';
 import '$lib/settings/settings.css';
 let exampleSection = $state('companion');
 let exampleRhythm = $state(true);
 let sampleName = $state('');
 let saved = $state(false);
 const colors = [ ['Background', '--background', '#201D29'], ['Panel', '--card', '#282432'], ['Elevated', '--popover', '#312C3C'], ['Lavender', '--primary', '#B7A9E7'], ['Ivory', '--foreground', '#F6F3EC'], ['Secondary text', '--text-secondary', '#D0C9DC'] ];
</script>
<svelte:head><title>Nolune — Design system</title></svelte:head>
{#if showBirth}<MoonBirth oncomplete={() => showBirth = false} />{/if}
<main class="system" inert={showBirth}>
 <header><a class="brand" href="/"><img src="/skins/moon/character.svg" alt="" width="32" height="32" />nolune</a><a href="/">Back to your companions ↗</a></header>
 <section class="intro"><div><p class="nl-eyebrow">Little Moon · Design system / 01</p><h1>A familiar language.<br />Room to grow.</h1><p>The shared visual foundation for Nolune’s client and landing. Calm surfaces, clear actions, and a little personality.</p></div><img src="/skins/moon/character.svg" width="180" height="180" alt="Little Moon" /></section>
 <nav aria-label="Design system sections"><a href="#palette">Palette</a><a href="#type">Typography</a><a href="#components">Components</a><a href="#conversation">Conversation</a><a href="#settings">Settings</a><a href="#principles">Principles</a></nav>
 <section id="palette"><p class="nl-eyebrow">01 / Color</p><h2>Plum, lavender, and breathing room.</h2><div class="swatches">{#each colors as [name, token, hex]}<article class="nl-panel swatch"><div style={`background:var(${token})`}></div><strong>{name}</strong><code>{token}</code><small>{hex}</small></article>{/each}</div></section>
 <section id="type"><p class="nl-eyebrow">02 / Typography</p><div class="two"><article class="nl-panel"><h2>Personality in the headlines.</h2><p>Fraunces · regular 400 · restrained tracking</p><p class="display-sample">A little more you.</p></article><article class="nl-panel"><h3>Clarity in the everyday.</h3><p>Bricolage Grotesque · body, buttons, navigation</p><p>Keep interface text direct and readable. Use sentence case and reserve the serif for welcoming moments.</p><code>JetBrains Mono — code and technical values</code></article></div></section>
 <section id="components"><p class="nl-eyebrow">03 / Components</p><h2>Useful, familiar, consistent.</h2><div class="two"><article class="nl-panel actions-panel"><h3>Actions</h3><div class="actions"><button class="nl-button nl-button-secondary" onclick={() => showBirth = true}>Replay moon arrival</button><button class="nl-button" onclick={() => saved = true}>Primary action</button><button class="nl-button nl-button-secondary" onclick={() => saved = false}>Reset example</button><button class="nl-button" disabled>Unavailable</button></div><p role="status">{saved ? 'Example action complete. No data was saved.' : 'Interactive examples only. No account changes.'}</p></article><article class="nl-panel"><label for="sample-name">Your name</label><input id="sample-name" class="nl-input" bind:value={sampleName} placeholder="What should Nolune call you?" /><p>{sampleName ? `Hello, ${sampleName}.` : 'Visible labels, comfortable spacing, and a clear focus ring.'}</p></article></div></section>
 <section id="conversation"><p class="nl-eyebrow">04 / Conversation</p><h2>Let the words do the work.</h2><p>Real Svelte AI Elements, styled for Little Moon. Try sending, stopping, attachments, and a failed send. This example runs locally without a backend.</p><ChatExample /></section>
 <section id="settings"><p class="nl-eyebrow">05 / Settings</p><h2>One panel, sectioned.</h2><p>Every settings page is one panel divided into rows: the section title and a one-line description on the left, its controls on the right. Sections are never separate cards, so uneven heights cannot leave gaps. The section nav is a segmented control. Example only; nothing here is saved.</p>
 <div class="settings-page ds-settings">
  <header class="settings-head"><h2 class="settings-title">Settings</h2><nav class="settings-nav" aria-label="Example settings sections">{#each [['companion', 'Companion'], ['connections', 'Connections'], ['advanced', 'Advanced']] as [id, label] (id)}<a href="#settings" class="settings-nav-link" class:settings-nav-active={exampleSection === id} aria-current={exampleSection === id ? 'page' : undefined} onclick={(e) => { e.preventDefault(); exampleSection = id; }}>{label}</a>{/each}</nav><p class="settings-lead">Presence, rhythm, initiative, and time.</p></header>
  <div class="settings-panel">
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Companion</h3><p class="section-desc">Little Moon, your familiar presence across devices.</p></div>
</div><div class="section-body"><div class="setting-row"><span class="setting-label" id="ds-rhythm-label">Learn my rhythm</span><div class="setting-input-row"><button class="setting-btn" role="switch" aria-checked={exampleRhythm} aria-labelledby="ds-rhythm-label" onclick={() => (exampleRhythm = !exampleRhythm)}>{exampleRhythm ? 'On' : 'Off'}</button></div><p class="setting-hint">Keeps a bounded summary of when you tend to write, so check-ins land at good moments.</p></div>
</div></section>
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Server <span class="owner-badge">This server</span></h3><p class="section-desc">Owner badges mark controls that apply to the whole server.</p></div>
</div><div class="section-body"><div class="setting-row"><label class="setting-label" for="ds-port">Port</label><div class="setting-input-row"><input class="setting-input" id="ds-port" type="number" value="26559" readonly /><button class="setting-btn" type="button" disabled>Save</button></div><p class="setting-hint">Inputs keep 16px text and a visible focus ring. Actions stay 44px tall.</p></div>
</div></section>
  </div>
 </div></section>
 <section id="principles"><p class="nl-eyebrow">06 / Principles</p><div class="two"><article class="nl-panel"><h3>A companion, with restraint.</h3><p>Use the moon as a recognizable presence. Keep working surfaces quiet. Use the same plum panels and lavender actions across settings, content, and conversation views. Keep loading, empty, and error states distinct.</p></article><article class="nl-panel"><h3>Accessible by default.</h3><p>44px controls, visible keyboard focus, readable secondary text, and reduced-motion support. Dialogs contain keyboard focus and restore it when closed. Pair every status color with words.</p></article></div></section>
 <footer>Implementation reference: docs/design-system.md · Tokens: client/src/lib/styles/tokens.css</footer>
</main>
<style>
.system{height:100%;overflow:auto;padding:0 max(24px,calc((100vw - 1080px)/2)) 48px;background:var(--background);scroll-behavior:smooth;scroll-padding-top:24px}header{display:flex;justify-content:space-between;align-items:center;padding:24px 0;border-bottom:1px solid var(--border);gap:16px;font-size:13px;color:var(--text-secondary)}.brand{display:flex;align-items:center;gap:8px;font:500 24px var(--font-body);color:var(--foreground)}.intro{display:flex;justify-content:space-between;gap:40px;align-items:center}.intro>div{max-width:650px}h1{font:400 clamp(2.5rem,5vw,4.5rem)/1.1 var(--font-display);letter-spacing:-.035em;margin:20px 0}h2{font:400 32px/1.2 var(--font-display);margin:12px 0 24px}h3{font:500 18px var(--font-body);margin:0 0 20px}p{font-size:15px;line-height:1.7;color:var(--text-secondary)}nav{display:flex;gap:24px;flex-wrap:wrap;padding-bottom:24px;border-bottom:1px solid var(--border);font-size:14px;color:var(--primary)}section{padding:40px 0}.swatches{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.swatch{padding:12px;display:grid;gap:6px}.swatch>div{height:80px;border-radius:8px;border:1px solid var(--border);margin-bottom:8px}code,small{color:var(--text-muted);font-size:12px}code{font-family:var(--font-mono)}.two{display:grid;grid-template-columns:1fr 1fr;gap:20px}.display-sample{font:400 36px var(--font-display);color:var(--foreground)}.actions-panel{display:flex;flex-direction:column;gap:20px}.actions-panel h3,.actions-panel p{margin:0}.actions{display:flex;flex-wrap:wrap;align-items:center;gap:12px}label{display:block;font-size:14px;margin-bottom:12px}.ds-settings{height:auto;padding:0;overflow:visible}footer{padding-top:24px;border-top:1px solid var(--border);font-size:12px;color:var(--text-muted);line-height:1.7}@media(max-width:650px){.two{grid-template-columns:1fr}.swatches{grid-template-columns:repeat(2,1fr)}.intro{gap:16px}.intro>img{width:80px;height:80px}h1{font-size:2.4rem}header>a:last-child{font-size:11px}nav{gap:16px}.system{padding-left:20px;padding-right:20px}section{padding:28px 0}}
</style>
