<script lang="ts">
 import MoonBirth from '$lib/components/onboarding/MoonBirth.svelte';
 let showBirth = $state(false);
 import ChatExample from '$lib/components/chat/ChatExample.svelte';
 import MemoryReceiptPanel from '$lib/components/memory/MemoryReceiptPanel.svelte';
 import type { RecalledMemory } from '$lib/api/types.js';
 // Sample receipt (#84): one memory per reason, one deleted source. Nothing here is fetched.
 const sampleReceipt: RecalledMemory[] = [
  { path: 'about/tea.md', source: 'about/tea.md', excerpt: 'Likes oolong, brews it at 85°C, never before noon.', reason: 'semantic', confidence: 'high', retrieved_at: new Date(Date.now() - 120_000).toISOString(), source_status: 'present' },
  { path: 'people/anna.md', source: 'people/anna.md', excerpt: 'Anna, colleague on the brief; prefers short check-ins.', reason: 'pinned', confidence: 'high', retrieved_at: new Date(Date.now() - 120_000).toISOString(), source_status: 'present' },
  { path: 'photos/sky.png', source: 'photos/sky.png.md', excerpt: 'Sky over Lisbon at dusk, taken from the balcony.', reason: 'linked_to', linked_from: 'about/tea.md', confidence: 'low', retrieved_at: new Date(Date.now() - 3 * 86_400_000).toISOString(), source_status: 'missing' },
 ];
 import '$lib/settings/settings.css';
 import { capabilityWarnings, presetTestCopy } from '$lib/models/presets.js';
 // Sample preset row (#28): chips from the real helper, a test result that never leaves the page.
 const examplePreset = { id: 'gpt', name: 'GPT-5.4', provider: 'openai', model: 'gpt-5.4' };
 const exampleWarnings = capabilityWarnings(examplePreset, { vision: true, documents: false, tools: true });
 let exampleTested = $state(false);
 const exampleTestCopy = presetTestCopy({ ok: true, preset: 'gpt', provider: 'openai', model: 'gpt-5.4', usage: { input_tokens: 8, output_tokens: 1 } }, examplePreset);
 import { COMPANION_KINDS, STATE_EXAMPLES, companionStatusText, initialCompanionState, reduceCompanion } from '$lib/companion/state.js';
 import SpaceRow from '$lib/components/computers/SpaceRow.svelte';
 import { STALE_HEARTBEAT_SECS, applyMachineEvent, buildSpaces, homeSpace } from '$lib/computers/spaces.js';
 import type { MachineInfo } from '$lib/api/types.js';
 // One documented event sequence per state, reduced by the real reducer so the gallery cannot drift.
 const companionStates = COMPANION_KINDS.map((k) => {
  const state = (STATE_EXAMPLES.find((e) => e.kind === k.kind)?.events ?? []).reduce(reduceCompanion, initialCompanionState());
  const busy = state.runs.length > 0 && state.kind !== 'waiting' && state.kind !== 'blocked' && state.kind !== 'offline';
  return { ...k, text: companionStatusText(state), avatar: busy ? '/skins/moon/thinking.svg' : '/skins/moon/character.svg' };
 });
 import CompanionRow from '$lib/components/federation/CompanionRow.svelte';
 import { peerView } from '$lib/federation/companions.js';
 import type { FederationPeer } from '$lib/api/types.js';
 // Companions (#108): peers as GET /api/federation/peers lists them, viewed at a fixed clock. Read-only; the section's actions need a running companion.
 const samplePeer = (companion_id: string, state: FederationPeer['state'], role: FederationPeer['role'], seenAgo: number | null, origins: string[]): FederationPeer => ({ companion_id, public_key: 'SN7Fvp7FYlYfvTUUW4vPFzy1jh9gtfDVlA7I3_QSj4U', state, role, pairing_id: '9f1c0b7e2a6d4c31', approved_origins: origins, pending_origin: state === 'pending' && role === 'issuer' ? 'http://localhost:26702' : undefined, created_at: 1_800_000_000 - 86_400, updated_at: 1_800_000_000 - 3_600, last_seen_at: seenAgo === null ? undefined : 1_800_000_000 - seenAgo, rotation_history: [] });
 const sampleCompanions = [
  samplePeer('TFccHElqXR1lkUBqQoQPWYxPSm1wPjCl8WXbgm_cQ7E', 'paired', 'issuer', 120, ['https://molinka.example']),
  samplePeer('_gNGE_IhVJx8y6mCBkyNM5_BhjuuTeIUwa6WQa8NZLs', 'pending', 'issuer', 30, []),
  samplePeer('yob7BCJNccQgNdznxaQZ_Rxn1k5ACU12hxmKeBKNhL0', 'pending', 'accepter', 45, ['http://localhost:26701']),
  samplePeer('SN7Fvp7FYlYfvTUUW4vPFzy1jh9gtfDVlA7I3_QSj4U', 'revoked', 'accepter', 86_400 * 3, []),
 ].map((peer) => peerView(peer, 1_800_000_000));
 import HandoffCard from '$lib/components/continuity/HandoffCard.svelte';
 import type { ContinuationPreview, HandoffAccepted, HandoffCard as HandoffCardData } from '$lib/api/types.js';
 // A handoff card (#82) with simulated computers and checks. The card only ever shows the server's record; here the "server" is these constants.
 const exampleNow = Math.floor(Date.now() / 1000);
 const exampleMachine = (machine_id: string, display_name: string, online: boolean, health: MachineInfo['health']): MachineInfo => ({ machine_id, display_name, custom_name: null, hostname: display_name, os: 'macos', platform: 'macos', location: 'desktop', screen_width: 2560, screen_height: 1440, permissions: null, capabilities: [], first_seen: exampleNow - 86400, last_seen: online ? exampleNow : exampleNow - 7200, instance_slug: 'companion', online, health, driver_version: null, cua_health: null });
 const exampleMachines = [exampleMachine('mac-a', 'studio', false, 'unavailable'), exampleMachine('mac-b', 'Travel Laptop', true, 'healthy'), exampleMachine('mac-c', 'old-mini', true, 'degraded')];
 const exampleSummary = (m: MachineInfo) => ({ machine_id: m.machine_id, display_name: m.display_name, known: true, online: m.online, health: m.health, platform: m.platform, last_seen: m.last_seen });
 const exampleHandoff = (): HandoffCardData => ({ record_id: 'task_example', goal: 'Rename the trip photos in the Trip folder', state: 'active', origin_chat_id: 'chat_example', origin: exampleSummary(exampleMachines[0]), completed_steps: ['Listed the folder: 214 photos', 'Drafted the naming scheme'], resources: [{ resource: { kind: 'memory', path: 'notes/trip.md' }, label: 'memory notes/trip.md', available: true }, { resource: { kind: 'machine_path', machine_id: 'mac-a', path: '/Volumes/Trip' }, label: '/Volumes/Trip on studio', available: false }], blockers: ['Needs the external drive', '/Volumes/Trip on studio cannot be found'], next_step: 'Rename IMG_* files to trip-<date>-<n>', required: { capabilities: ['screenshot', 'left_click', 'type', 'key', 'file_read', 'file_list'], permissions: ['screen_capture', 'accessibility'] }, decision: null, bound_to: null, offered: true, created_at: exampleNow - 3600, updated_at: exampleNow - 900 });
 let exampleCard = $state<HandoffCardData>(exampleHandoff());
 async function examplePreview(machineId: string): Promise<ContinuationPreview> {
  const destination = exampleSummary(exampleMachines.find((m) => m.machine_id === machineId) ?? exampleMachines[1]);
  const checks: ContinuationPreview['checks'] = destination.online && destination.health !== 'degraded'
   ? [{ kind: { kind: 'permission_prompt', permission: 'screen_capture' }, severity: 'approval', detail: `${destination.display_name} will ask for Screen Recording before the first action` }, { kind: { kind: 'resource_elsewhere', machine_id: 'mac-a' }, severity: 'blocking', detail: `/Volumes/Trip is on studio, which is not connected; ${destination.display_name} cannot reach it` }]
   : [{ kind: { kind: destination.online ? 'machine_not_responding' : 'machine_offline' }, severity: 'blocking', detail: destination.online ? `${destination.display_name} is connected but not responding` : `${destination.display_name} is offline` }];
  const ready = !checks.some((c) => c.severity === 'blocking');
  return { card: exampleCard, destination, checks, ready };
 }
 async function exampleAccept(machineId: string): Promise<HandoffAccepted> {
  const destination = exampleSummary(exampleMachines.find((m) => m.machine_id === machineId) ?? exampleMachines[1]);
  const card: HandoffCardData = { ...exampleCard, decision: { kind: 'accepted', machine_id: machineId, run_id: 'run_example', at: exampleNow, outcome: null }, bound_to: destination, updated_at: exampleNow };
  return { card, run: { version: 1, id: 'run_example', trigger: { kind: 'handoff', handoff_id: card.record_id }, reason: `continue on ${destination.display_name}`, target: { kind: 'machine', machine_id: machineId }, dedupe_key: 'handoff:task_example', status: { kind: 'running' }, attempt: 1, started_at: exampleNow, approvals: [] }, already_running: false };
 }
 const exampleKeep = async (): Promise<HandoffCardData> => ({ ...exampleCard, decision: { kind: 'kept', machine_id: 'mac-a', at: exampleNow }, offered: false });
 const exampleDismiss = async (): Promise<HandoffCardData> => ({ ...exampleCard, decision: { kind: 'dismissed', at: exampleNow }, offered: false });
 // A resume suggestion (#83): the ritual's pick in the server's words, leading to the card above. Answering it here only hides the example.
 import ResumeBanner from '$lib/components/continuity/ResumeBanner.svelte';
 import type { ResumeOffer } from '$lib/api/types.js';
 const exampleResume = (): ResumeOffer => ({ id: 'sug_example', record_id: 'task_example', goal: 'Rename the trip photos in the Trip folder', trigger: { kind: 'opened_after_break', away_secs: 3 * 3600 }, why_now: 'You opened Nolune after 3 hours away.', why_this: 'high priority, due in 2 days, 1 stated blocker, updated 15 minutes ago, Travel Laptop can take it', destination_id: 'mac-b', suggested_at: exampleNow - 120, card: exampleHandoff() });
 let exampleOffer = $state<ResumeOffer | null>(exampleResume());
 const answerExample = async () => { exampleOffer = null; };
 let exampleSection = $state('companion');
 // Connected spaces (#80): sample records in the GET /machines shape, viewed by the real helpers at a fixed clock. Nothing here is a live computer.
 const spacesNow = 1_800_000_000;
 const sampleDesktop = (over: Partial<MachineInfo>): MachineInfo => ({ machine_id: 'sample', display_name: 'studio', custom_name: null, hostname: 'studio', os: 'macOS 15.1', platform: 'macos', location: 'desktop', screen_width: 2560, screen_height: 1440, permissions: { accessibility: 'granted', screen_capture: 'granted' }, capabilities: ['screenshot', 'left_click', 'type', 'bash'], first_seen: spacesNow - 86400, last_seen: spacesNow - 5, instance_slug: 'companion', online: true, health: 'healthy', driver_version: null, cua_health: null, ...over });
 let sampleMachines = $state<MachineInfo[]>([
  sampleDesktop({ machine_id: 'sample-studio', custom_name: 'Studio Mac', display_name: 'Studio Mac' }),
  sampleDesktop({ machine_id: 'sample-den', hostname: 'den', display_name: 'den', last_seen: spacesNow - STALE_HEARTBEAT_SECS - 7, health: 'degraded' }),
  sampleDesktop({ machine_id: 'sample-kiosk', hostname: 'kiosk', display_name: 'kiosk', os: 'Windows 11', platform: 'windows', screen_width: 1920, screen_height: 1080, permissions: { accessibility: 'denied', screen_capture: 'granted' } }),
  sampleDesktop({ machine_id: 'sample-laptop', hostname: 'laptop', display_name: 'laptop', os: 'Ubuntu 24.04', platform: 'linux', online: false, health: 'unavailable', last_seen: spacesNow - 7200 }),
 ]);
 const sampleHome = homeSpace({ connected: true, address: 'nolune.local:26559', version: '0.36.0', companionName: 'Luna', nowSeconds: spacesNow });
 const sampleSpaces = $derived(buildSpaces(sampleMachines, spacesNow, sampleHome, 'Luna'));
 // The sample rename and forget never leave the page: they apply the same events the server would send.
 const sampleRename = (id: string) => async (name: string | null) => {
  const machine = sampleMachines.find((m) => m.machine_id === id);
  if (!machine) return;
  sampleMachines = applyMachineEvent(sampleMachines, { type: 'machine_updated', instance_slug: 'companion', machine: { ...machine, custom_name: name, display_name: name ?? machine.hostname } });
 };
 const sampleForget = (id: string) => async () => {
  sampleMachines = applyMachineEvent(sampleMachines, { type: 'machine_forgotten', instance_slug: 'companion', machine_id: id });
 };
 let exampleRhythm = $state(true);
 let sampleName = $state('');
 let saved = $state(false);
 const colors = [ ['Background', '--background', '#201D29'], ['Panel', '--card', '#282432'], ['Elevated', '--popover', '#312C3C'], ['Lavender', '--primary', '#B7A9E7'], ['Ivory', '--foreground', '#F6F3EC'], ['Secondary text', '--text-secondary', '#D0C9DC'] ];
</script>
<svelte:head><title>Nolune — Design system</title></svelte:head>
{#if showBirth}<MoonBirth oncomplete={() => showBirth = false} />{/if}
<main class="system" inert={showBirth}>
 <header><a class="brand" href="/"><img src="/skins/moon/character.svg" alt="" width="32" height="32" />nolune</a><a href="/">Back to your companions ↗</a></header>
 <section class="intro"><div><p class="nl-eyebrow">Little Moon · Design system / 01</p><h1>A familiar language.<br />Room to grow.</h1><p>The shared visual foundation for Nolune’s client and landing. Calm surfaces, clear actions, and a little personality.</p></div><img src="/skins/moon/character.svg" width="180" height="180" alt="Little Moon" /></section>
 <nav aria-label="Design system sections"><a href="#palette">Palette</a><a href="#type">Typography</a><a href="#components">Components</a><a href="#conversation">Conversation</a><a href="#settings">Settings</a><a href="#companion">Companion state</a><a href="#spaces">Connected spaces</a><a href="#handoff">Handoff</a><a href="#principles">Principles</a></nav>
 <section id="palette"><p class="nl-eyebrow">01 / Color</p><h2>Plum, lavender, and breathing room.</h2><div class="swatches">{#each colors as [name, token, hex]}<article class="nl-panel swatch"><div style={`background:var(${token})`}></div><strong>{name}</strong><code>{token}</code><small>{hex}</small></article>{/each}</div></section>
 <section id="type"><p class="nl-eyebrow">02 / Typography</p><div class="two"><article class="nl-panel"><h2>Personality in the headlines.</h2><p>Fraunces · regular 400 · restrained tracking</p><p class="display-sample">A little more you.</p></article><article class="nl-panel"><h3>Clarity in the everyday.</h3><p>Bricolage Grotesque · body, buttons, navigation</p><p>Keep interface text direct and readable. Use sentence case and reserve the serif for welcoming moments.</p><code>JetBrains Mono — code and technical values</code></article></div></section>
 <section id="components"><p class="nl-eyebrow">03 / Components</p><h2>Useful, familiar, consistent.</h2><div class="two"><article class="nl-panel actions-panel"><h3>Actions</h3><div class="actions"><button class="nl-button nl-button-secondary" onclick={() => showBirth = true}>Replay moon arrival</button><button class="nl-button" onclick={() => saved = true}>Primary action</button><button class="nl-button nl-button-secondary" onclick={() => saved = false}>Reset example</button><button class="nl-button" disabled>Unavailable</button></div><p role="status">{saved ? 'Example action complete. No data was saved.' : 'Interactive examples only. No account changes.'}</p></article><article class="nl-panel"><label for="sample-name">Your name</label><input id="sample-name" class="nl-input" bind:value={sampleName} placeholder="What should Nolune call you?" /><p>{sampleName ? `Hello, ${sampleName}.` : 'Visible labels, comfortable spacing, and a clear focus ring.'}</p></article></div></section>
 <section id="conversation"><p class="nl-eyebrow">04 / Conversation</p><h2>Let the words do the work.</h2><p>Real Svelte AI Elements, styled for Little Moon. Try sending, stopping, attachments, and a failed send. This example runs locally without a backend.</p><ChatExample />
 <article class="nl-panel receipt-sample"><h3>Memory receipt</h3><p>Under an assistant reply, “Why did Nolune remember this?” lists the memories that shaped it: the canonical source, the excerpt that was recalled, how retrieval found it, a confidence bucket (never a score) and when. A source forgotten since the reply is said so. In the app each entry carries Inspect, Correct, Pin, Exclude from proactive use and Forget; a correction that conflicts with an earlier one shows both statements and asks which stays. Sample data; the controls need a running companion.</p><MemoryReceiptPanel slug="example" chatId="example" messageId="example-receipt" memories={sampleReceipt} readonly /></article></section>
 <section id="settings"><p class="nl-eyebrow">05 / Settings</p><h2>One panel, sectioned.</h2><p>Every settings page is one panel divided into rows: the section title and a one-line description on the left, its controls on the right. Sections are never separate cards, so uneven heights cannot leave gaps. The section nav is a segmented control. Example only; nothing here is saved.</p>
 <div class="settings-page ds-settings">
  <header class="settings-head"><h2 class="settings-title">Settings</h2><nav class="settings-nav" aria-label="Example settings sections">{#each [['companion', 'Companion'], ['connections', 'Connections'], ['advanced', 'Advanced']] as [id, label] (id)}<a href="#settings" class="settings-nav-link" class:settings-nav-active={exampleSection === id} aria-current={exampleSection === id ? 'page' : undefined} onclick={(e) => { e.preventDefault(); exampleSection = id; }}>{label}</a>{/each}</nav><p class="settings-lead">Presence, rhythm, initiative, and time.</p></header>
  <div class="settings-panel">
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Companion</h3><p class="section-desc">Little Moon, your familiar presence across devices.</p></div>
</div><div class="section-body"><div class="setting-row"><span class="setting-label" id="ds-rhythm-label">Learn my rhythm</span><div class="setting-input-row"><button class="setting-btn" role="switch" aria-checked={exampleRhythm} aria-labelledby="ds-rhythm-label" onclick={() => (exampleRhythm = !exampleRhythm)}>{exampleRhythm ? 'On' : 'Off'}</button></div><p class="setting-hint">Keeps a bounded summary of when you tend to write, so check-ins land at good moments.</p></div>
</div></section>
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Models</h3><p class="section-desc">A preset row says what its model cannot do as chips, and Test sends one short request without touching any chat.</p></div>
</div><div class="section-body"><ul class="preset-list" aria-label="Example preset"><li class="preset-row"><label class="preset-field">Name<input class="ext-input" type="text" value={examplePreset.name} readonly /></label><label class="preset-field">Provider<select class="setting-input" disabled><option>OpenAI</option></select></label><label class="preset-field preset-field-model">Model id<input class="ext-input" type="text" value={examplePreset.model} readonly /></label><button class="setting-btn setting-btn-danger preset-remove" type="button" disabled>Remove</button><div class="preset-foot">{#each exampleWarnings as warning (warning.id)}<span class="preset-chip" title={warning.detail}>{warning.chip}</span>{/each}<button class="nl-button-secondary preset-test" type="button" onclick={() => (exampleTested = !exampleTested)}>{exampleTested ? 'Reset' : 'Test'}</button>{#if exampleTested}<span class="preset-result preset-result-ok" role="status">{exampleTestCopy.text} (example)</span>{/if}</div></li></ul>{#each exampleWarnings as warning (warning.id)}<p class="setting-hint setting-warning">{warning.detail}</p>{/each}</div></section>
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Companions</h3><p class="section-desc">Peer companions this one is paired with (#108): each row is its id, its state beside a color, who invited whom, where it is reached, and when something it signed last verified here. Sample records; Confirm and Revoke need a running companion.</p></div>
</div><div class="section-body"><ul class="ds-companions" aria-label="Sample companions">{#each sampleCompanions as peer (peer.id)}<CompanionRow {peer} />{/each}</ul></div></section>
   <section class="settings-section"><div class="section-header"><div><h3 class="section-label">Server <span class="owner-badge">This server</span></h3><p class="section-desc">Owner badges mark controls that apply to the whole server.</p></div>
</div><div class="section-body"><div class="setting-row"><label class="setting-label" for="ds-port">Port</label><div class="setting-input-row"><input class="setting-input" id="ds-port" type="number" value="26559" readonly /><button class="setting-btn" type="button" disabled>Save</button></div><p class="setting-hint">Inputs keep 16px text and a visible focus ring. Actions stay 44px tall.</p></div>
</div></section>
  </div>
 </div></section>
 <section id="companion"><p class="nl-eyebrow">06 / Companion state</p><h2>The moon says what is really happening.</h2><p>Every state is derived from a runtime event and resolved in this priority order; the sentence beside each moon is its accessible status text, so the state reads without motion. Examples are reduced live by <code>lib/companion/state.js</code>. Read-only.</p><ol class="states">{#each companionStates as s, i (s.kind)}<li class="nl-panel state"><img src={s.avatar} alt="" width="48" height="48" /><div><strong><code class="state-rank">{i + 1}</code>{s.label}</strong><p class="state-text">{s.text}</p><small>{s.source}</small></div></li>{/each}</ol></section>
 <section id="spaces"><p class="nl-eyebrow">07 / Connected spaces</p><h2>Every place it can act, one list.</h2><p>The Computers tab and Settings › Connections list the server home first, then desktops: online by name, then offline by last seen. Each row pairs its state word with a color, shows what the desktop reported (permissions, actions, Cua driver), and carries one hint per thing to do. Rename is inline; Forget, on an offline row only, asks once before it drops the record. Rows are viewed by <code>lib/computers/spaces.js</code> from sample records at a fixed clock; renaming or forgetting here changes nothing on a server.</p><ul class="spaces">{#each sampleSpaces as space (space.id)}<SpaceRow {space} onrename={space.canRename ? sampleRename(space.id) : undefined} onforget={space.canForget ? sampleForget(space.id) : undefined} />{/each}</ul></section>
 <section id="handoff"><p class="nl-eyebrow">08 / Handoff</p><h2>Pick a task up where you are.</h2><p>A handoff card (#82) is derived from the task record and the known computers, so it reads the same while the computer it started on is offline. Continue here, Continue on…, Keep there, and Dismiss are the four decisions; a preview names the destination and every check before anything runs. Example only, with simulated computers: studio is offline, Travel Laptop is ready, old-mini is not responding.</p><div class="handoff-example"><HandoffCard card={exampleCard} machines={exampleMachines} hereId="mac-b" now={exampleNow} onpreview={examplePreview} onaccept={exampleAccept} onkeep={exampleKeep} ondismiss={exampleDismiss} onupdated={(card) => (exampleCard = card)} /><button class="nl-button nl-button-secondary" onclick={() => (exampleCard = exampleHandoff())}>Reset example</button></div><h3>Resume my work</h3><p>The opt-in ritual (#83) offers at most one task per trigger, from the task records alone: it says which task, why it was picked (priority, deadline, blockers, recency, a ready computer), and why now (you asked, you came back after a break, a computer the task names reconnected). Review and continue leads to the handoff card above; Not now, Snooze, and Never this task answer the ritual. Example only.</p><div class="handoff-example">{#if exampleOffer}<ResumeBanner offer={exampleOffer} now={exampleNow} reviewHref="#handoff" onrefuse={answerExample} onsnooze={answerExample} ondismiss={answerExample} />{:else}<p>Answered. Nothing was continued.</p>{/if}<button class="nl-button nl-button-secondary" onclick={() => (exampleOffer = exampleResume())}>Reset example</button></div></section>
 <section id="principles"><p class="nl-eyebrow">09 / Principles</p><div class="two"><article class="nl-panel"><h3>A companion, with restraint.</h3><p>Use the moon as a recognizable presence. Keep working surfaces quiet. Use the same plum panels and lavender actions across settings, content, and conversation views. Keep loading, empty, and error states distinct.</p></article><article class="nl-panel"><h3>Accessible by default.</h3><p>44px controls, visible keyboard focus, readable secondary text, and reduced-motion support. Dialogs contain keyboard focus and restore it when closed. Pair every status color with words.</p></article></div></section>
 <footer>Implementation reference: docs/design-system.md · Tokens: client/src/lib/styles/tokens.css</footer>
</main>
<style>
.handoff-example{display:flex;flex-direction:column;gap:12px;max-width:720px;align-items:flex-start}.handoff-example>:global(.handoff),.handoff-example>:global(.resume){width:100%}.system{height:100%;overflow:auto;padding:0 max(24px,calc((100vw - 1080px)/2)) 48px;background:var(--background);scroll-behavior:smooth;scroll-padding-top:24px}header{display:flex;justify-content:space-between;align-items:center;padding:24px 0;border-bottom:1px solid var(--border);gap:16px;font-size:13px;color:var(--text-secondary)}.brand{display:flex;align-items:center;gap:8px;font:500 24px var(--font-body);color:var(--foreground)}.intro{display:flex;justify-content:space-between;gap:40px;align-items:center}.intro>div{max-width:650px}h1{font:400 clamp(2.5rem,5vw,4.5rem)/1.1 var(--font-display);letter-spacing:-.035em;margin:20px 0}h2{font:400 32px/1.2 var(--font-display);margin:12px 0 24px}h3{font:500 18px var(--font-body);margin:0 0 20px}p{font-size:15px;line-height:1.7;color:var(--text-secondary)}nav{display:flex;gap:24px;flex-wrap:wrap;padding-bottom:24px;border-bottom:1px solid var(--border);font-size:14px;color:var(--primary)}section{padding:40px 0}.swatches{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.swatch{padding:12px;display:grid;gap:6px}.swatch>div{height:80px;border-radius:8px;border:1px solid var(--border);margin-bottom:8px}code,small{color:var(--text-muted);font-size:12px}code{font-family:var(--font-mono)}.two{display:grid;grid-template-columns:1fr 1fr;gap:20px}.display-sample{font:400 36px var(--font-display);color:var(--foreground)}.actions-panel{display:flex;flex-direction:column;gap:20px}.actions-panel h3,.actions-panel p{margin:0}.actions{display:flex;flex-wrap:wrap;align-items:center;gap:12px}label{display:block;font-size:14px;margin-bottom:12px}.ds-settings{height:auto;padding:0;overflow:visible}.states{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:1fr 1fr;gap:16px}.spaces,.ds-companions{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px;max-width:720px}.state{display:flex;gap:16px;padding:16px;align-items:flex-start}.state>img{flex-shrink:0}.state strong{display:flex;align-items:center;gap:8px;font-size:14px;color:var(--foreground)}.state-rank{font-size:12px;color:var(--text-muted);min-width:1.5em}.state-text{margin:4px 0 8px;font-size:14px;color:var(--foreground)}.state small{display:block;line-height:1.5}footer{padding-top:24px;border-top:1px solid var(--border);font-size:12px;color:var(--text-muted);line-height:1.7}@media(max-width:650px){.two{grid-template-columns:1fr}.states{grid-template-columns:1fr}.swatches{grid-template-columns:repeat(2,1fr)}.intro{gap:16px}.intro>img{width:80px;height:80px}h1{font-size:2.4rem}header>a:last-child{font-size:11px}nav{gap:16px}.system{padding-left:20px;padding-right:20px}section{padding:28px 0}}
.receipt-sample{max-width:800px;margin-top:20px}.receipt-sample h3{margin:0 0 8px;font:500 18px/1.3 var(--font-body)}.receipt-sample p{margin:0 0 12px;font-size:14px;line-height:1.6;color:var(--text-secondary)}
</style>
