import { randomBytes } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { paths } from './paths.ts';

export interface Config {
	/** better-auth secret, generated by `nolune init`. */
	authSecret: string;
	anthropicApiKey?: string;
	/** For `nolune generate image` with the openai image provider. */
	openaiApiKey?: string;
	openrouterApiKey?: string;
	/**
	 * The Claude Code executable that chats on the Claude plan run (claude-plan.ts). Found on the
	 * PATH and in the usual install folders when not set.
	 */
	claudePath?: string;
	/**
	 * The Codex executable that chats on the ChatGPT plan run (chatgpt-plan.ts). Found on the PATH
	 * and in the usual install folders when not set.
	 */
	codexPath?: string;
	/**
	 * What `nolune generate image` uses, as `<provider>/<model>`. Defaults to
	 * `openai/gpt-image-2.5-flare`.
	 */
	imageModel?: string;
	/** Extra environment variables for commands the agent runs (e.g. FIRECRAWL_API_KEY). */
	commandEnv?: Record<string, string>;
	/** Where `nolune start` listens. Defaults: 127.0.0.1:5780 (put a tunnel or proxy in front). */
	host?: string;
	port?: number;
	/** Public URL people open, e.g. https://nolune.example.com. Defaults to http://localhost:<port>. */
	origin?: string;
}

export const DEFAULT_PORT = 5780;

/** Where each provider's API key is kept, and the environment variable used when it isn't. */
export const API_KEYS = {
	anthropic: { label: 'Anthropic', field: 'anthropicApiKey', env: 'ANTHROPIC_API_KEY' },
	openai: { label: 'OpenAI', field: 'openaiApiKey', env: 'OPENAI_API_KEY' },
	openrouter: { label: 'OpenRouter', field: 'openrouterApiKey', env: 'OPENROUTER_API_KEY' }
} as const satisfies Record<string, { label: string; field: keyof Config; env: string }>;

export type ApiKeyProvider = keyof typeof API_KEYS;

export function isApiKeyProvider(value: string): value is ApiKeyProvider {
	return Object.hasOwn(API_KEYS, value);
}

/** The key in use: config.json's, else the environment's. Read on every call, so changes apply at once. */
export function configuredApiKey(
	provider: ApiKeyProvider
): { key: string; source: 'config' | 'env' } | null {
	const { field, env } = API_KEYS[provider];
	let saved: string | undefined;
	try {
		saved = readConfig()[field];
	} catch {
		// not set up yet: only the environment can have one
	}
	if (saved) return { key: saved, source: 'config' };
	const fromEnv = process.env[env];
	return fromEnv ? { key: fromEnv, source: 'env' } : null;
}

/** How a missing or rejected key gets fixed, for messages people and the agent see. */
export function apiKeyHelp(provider: ApiKeyProvider): string {
	return `An admin can add one under Models & keys in nolune, or with \`nolune key set ${provider}\`.`;
}

export function configExists(): boolean {
	return existsSync(paths.config);
}

export function readConfig(): Config {
	if (!configExists()) {
		throw new Error(`No config at ${paths.config}. Run \`nolune init\` first.`);
	}
	return JSON.parse(readFileSync(paths.config, 'utf8')) as Config;
}

export function writeConfig(config: Config): void {
	mkdirSync(paths.home, { recursive: true });
	writeFileSync(paths.config, JSON.stringify(config, null, '\t') + '\n', { mode: 0o600 });
	chmodSync(paths.config, 0o600);
}

/** Creates config.json with a fresh auth secret if it doesn't exist yet. */
export function initConfig(): { created: boolean } {
	if (configExists()) return { created: false };
	writeConfig({ authSecret: randomBytes(32).toString('base64url') });
	return { created: true };
}

export function updateConfig(change: (config: Config) => void): Config {
	const config = readConfig();
	change(config);
	writeConfig(config);
	return config;
}
