import { randomBytes } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { paths } from './paths.ts';

export interface Config {
	/** better-auth secret, generated by `btw init`. */
	authSecret: string;
	anthropicApiKey?: string;
	/** For `btw generate image` with the openai image provider. */
	openaiApiKey?: string;
	/**
	 * What `btw generate image` uses, as `<provider>/<model>`. Defaults to
	 * `openai/gpt-image-2.5-flare`.
	 */
	imageModel?: string;
	/** Extra environment variables for commands the agent runs (e.g. FIRECRAWL_API_KEY). */
	commandEnv?: Record<string, string>;
	/** Where `btw start` listens. Defaults: 127.0.0.1:5780 (put a tunnel or proxy in front). */
	host?: string;
	port?: number;
	/** Public URL people open, e.g. https://btw.example.com. Defaults to http://localhost:<port>. */
	origin?: string;
}

export const DEFAULT_PORT = 5780;

export function configExists(): boolean {
	return existsSync(paths.config);
}

export function readConfig(): Config {
	if (!configExists()) {
		throw new Error(`No config at ${paths.config}. Run \`btw init\` first.`);
	}
	return JSON.parse(readFileSync(paths.config, 'utf8')) as Config;
}

export function writeConfig(config: Config): void {
	mkdirSync(paths.home, { recursive: true });
	writeFileSync(paths.config, JSON.stringify(config, null, '\t') + '\n', { mode: 0o600 });
	chmodSync(paths.config, 0o600);
}

/** Creates config.json with a fresh auth secret if it doesn't exist yet. */
export function initConfig(): { created: boolean } {
	if (configExists()) return { created: false };
	writeConfig({ authSecret: randomBytes(32).toString('base64url') });
	return { created: true };
}

export function updateConfig(change: (config: Config) => void): Config {
	const config = readConfig();
	change(config);
	writeConfig(config);
	return config;
}
