import { AVATARS } from './avatars.ts';
import { avatarTint } from './tint.ts';

/**
 * The web's colors for nolune for iOS (ios/Shared/Palettes.swift): the variables in layout.css its
 * native screens use, in light and dark, and each avatar's tint of them (tint.ts), as a profile's
 * pages have them on the web. `node scripts/ios-avatars.ts` writes the file; a test checks it's
 * current.
 */

/** The variables, by their name in layout.css, in the order Palette.Colors declares them. */
export const PALETTE_NAMES = [
	'background',
	'foreground',
	'card',
	'popover',
	'primary',
	'primary-foreground',
	'secondary',
	'muted',
	'muted-foreground',
	'accent',
	'destructive',
	'border',
	'input',
	'ring',
	'sidebar',
	'sidebar-accent',
	'sidebar-border',
	'bubble',
	'composer',
	'warning'
] as const;

type Mode = 'light' | 'dark';
type Colors = Record<string, string>;

/** A variable's light (`:root`) and dark (`.dark`) values in a stylesheet, as written. */
function values(stylesheet: string, name: string): Record<Mode, string> {
	const [light, dark] = [...stylesheet.matchAll(new RegExp(`--${name}:\\s*([^;]+);`, 'g'))].map(
		(match) => match[1].trim()
	);
	if (!light || !dark) throw new Error(`--${name} needs a light and a dark value`);
	return { light, dark };
}

/** `Shade(0xRRGGBB)`, or with its opacity, from `#rrggbb` or `rgb(r g b / a)`. */
export function swiftShade(css: string): string {
	const hex = /^#([0-9a-f]{6})$/i.exec(css);
	if (hex) return `Shade(0x${hex[1].toUpperCase()})`;
	const rgb = /^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)\s*\/\s*([\d.]+)\s*\)$/.exec(css);
	if (rgb) {
		const channels = rgb
			.slice(1, 4)
			.map((c) => Number(c).toString(16).padStart(2, '0').toUpperCase())
			.join('');
		return `Shade(0x${channels}, ${Number(rgb[4])})`;
	}
	throw new Error(`A color Palette.Shade can't take: ${css}`);
}

const camel = (name: string) => name.replace(/-(\w)/g, (_, c: string) => c.toUpperCase());

function swiftColors(colors: Colors, indent: string): string {
	return [
		'Colors(',
		PALETTE_NAMES.map((name) => `${indent}\t${camel(name)}: ${swiftShade(colors[name])}`).join(
			',\n'
		),
		`${indent})`
	].join('\n');
}

function swiftPalette(light: Colors, dark: Colors, indent: string): string {
	return [
		'Palette(',
		`${indent}\tlight: ${swiftColors(light, `${indent}\t`)},`,
		`${indent}\tdark: ${swiftColors(dark, `${indent}\t`)}`,
		`${indent})`
	].join('\n');
}

/** Palettes.swift, from the colors in the web's layout.css. */
export function iosPaletteSource(stylesheet: string): string {
	const plain: Record<Mode, Colors> = { light: {}, dark: {} };
	for (const name of PALETTE_NAMES) {
		const { light, dark } = values(stylesheet, name);
		plain.light[name] = light;
		plain.dark[name] = dark;
	}
	const tinted = AVATARS.map((avatar) => {
		const tint = avatarTint(avatar, stylesheet);
		const palette = swiftPalette(
			{ ...plain.light, ...tint.light },
			{ ...plain.dark, ...tint.dark },
			'\t\t'
		);
		return `\t\t"${avatar}": ${palette}`;
	});
	return [
		'// Generated by scripts/ios-avatars.ts from the colors in packages/web/src/routes/layout.css and',
		"// the tint in packages/core/src/tint.ts. Don't edit it: change those, and run the script.",
		'',
		'extension Palette {',
		"\t/// The web's colors, as layout.css has them.",
		`\tstatic let plain = ${swiftPalette(plain.light, plain.dark, '\t')}`,
		'',
		"\t/// Each avatar's: the greys tinted with its hue, as a profile's pages are on the web.",
		'\tstatic let tinted: [String: Palette] = [',
		tinted.join(',\n'),
		'\t]',
		'}',
		''
	].join('\n');
}
